monitor_targets:
  - name: nginx-service
    url: "http://<your-server-ip>:80"
    type: "docker"

email:
  sender: "your@gmail.com"
  password: "your-app-password"
  receiver: "your@gmail.com"

auto_fix:
  docker_container_name: "nginx-container"
